language: java

before_install:
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"

script:
  - "mvn test integration-test -Djava.io.tmpdir=./folder -Pintegration-tests"


after_script: bash <(curl -s https://codecov.io/bash)